import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Session from "@/providers/SessionProvider";
import { DarkModeProvider } from "@/contexts/DarkModeContext";
import { SelectedFiltersProvider } from "@/contexts/SelectedFiltersContext";
import { WallpaperProvider } from "@/contexts/WallpaperContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Session>
          <DarkModeProvider>
            <SelectedFiltersProvider>
              <WallpaperProvider>{children}</WallpaperProvider>
            </SelectedFiltersProvider>
          </DarkModeProvider>
        </Session>
      </body>
    </html>
  );
}
